version: "3.9"

services:
  db:
    image: postgres:15
    container_name: stockwise_db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: stockwise_api
    environment:
      APP_INTERNAL_PORT: ${APP_INTERNAL_PORT}
    command: >
      sh -c "python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:${APP_INTERNAL_PORT}"
    volumes:
      - .:/app
    ports:
      - "${APP_EXTERNAL_PORT}:${APP_INTERNAL_PORT}"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
