# Generated by Django 5.2.11 on 2026-03-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='lot_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
